In [60]:
import torch
import numpy as np
def create_mask(x_len, y_len):
        # a mask of shape x_len * y_len
        device = x_len.device
        max_x_len = x_len.max()
        max_y_len = y_len.max()

        x_max = torch.arange(max_x_len, device=x_len.device)[None, :]

        x_mask = torch.arange(max_x_len, device=x_len.device)[None, :] < x_len[:, None]
        print("x_mask:")
        print(x_mask)
        y_mask = torch.arange(max_y_len, device=x_len.device)[None, :] < y_len[:, None]
        print("y_mask:")
        print(y_mask)
        x_mask.bool()
        y_mask.bool()
        # print(x_mask)
        print("~x_mask[:, :, None]")
        print(~x_mask[:, :, None])
        print("y_mask[:, None, :]")
        print(y_mask[:, None, :])
        mask = (~x_mask[:, :, None] * y_mask[:, None, :]).byte()

        return mask.bool()
x_len = np.array([5,4,3])
y_len = np.array([3,3,3])
x = torch.from_numpy(x_len)
y = torch.from_numpy(y_len)
create_mask(x_len=x,y_len=y)

x_mask:
tensor([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False],
        [ True,  True,  True, False, False]])
y_mask:
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
~x_mask[:, :, None]
tensor([[[False],
         [False],
         [False],
         [False],
         [False]],

        [[False],
         [False],
         [False],
         [False],
         [ True]],

        [[False],
         [False],
         [False],
         [ True],
         [ True]]])
y_mask[:, None, :]
tensor([[[True, True, True]],

        [[True, True, True]],

        [[True, True, True]]])


tensor([[[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False]],

        [[False, False, False],
         [False, False, False],
         [False, False, False],
         [False, False, False],
         [ True,  True,  True]],

        [[False, False, False],
         [False, False, False],
         [False, False, False],
         [ True,  True,  True],
         [ True,  True,  True]]])